version: 0.0
os: linux
files:
  - source: deploy/cp-salesforce-service.conf
    destination: /etc/init/
  - source: /
    destination: /opt/cp-salesforce-service
#hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies
#      timeout: 300
#      runas: root
#    - location: scripts/start_server
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root

